# Generated by Django 2.1.1 on 2018-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
                ('male_status', models.BooleanField()),
                ('female_status', models.BooleanField()),
                ('japanese_status', models.BooleanField()),
                ('english_status', models.BooleanField()),
                ('chinese_status', models.BooleanField()),
                ('korean_status', models.BooleanField()),
                ('comment', models.CharField(max_length=40, verbose_name='コメント')),
                ('update', models.DateTimeField(verbose_name='更新日')),
            ],
        ),
    ]
