# Generated by Django 2.1.1 on 2018-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
