# Generated by Django 2.1 on 2018-08-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='position',
            name='update',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
    ]
